### ISSUE TITLE
no funciona con este ruc 1790219526001

### ISSUE THREAD

**Issue by klascano** [maniac787/validacion-cedula-ruc-ecuador-java#1]
ruc de SIEMENS S.A. activo segun la pagina del sri, devuelve falta siempre

**Comment by maniac787** [comment]
![image](https://user-images.githubusercontent.com/882223/131873774-f5ab5980-8dfa-4684-9f86-b679b8f16b18.png)

Se actualiza el código, gracias por la alerta.

**Comment by klascano** [comment]
Gracias la revisión.
